### ISSUE TITLE
travis issue

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Lora.jl#101]
@IainNZ, after trying to push some changes in metadata on the basis of a bug fix made by @davidanthoff, I see the following error appearing (I didn't touch .travis.yml, and things were working before, so not sure what is going wrong):

'''
$ julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Lora"))`); Pkg.pin("Lora"); Pkg.resolve()'
INFO: Initializing package repository /home/travis/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Creating Lora branch pinned.ea1d014d.tmp
WARNING: julia is fixed at 0.4.0-pre+7078 conflicting with requirement for Lora: [0.3.0,0.4.0-)
```

**Comment by IainNZ** [comment]
Oh you committed directly to METADATA? You really shouldn't do that, everyone is expected to do PRs first

**Comment by scidom** [comment]
Ah, sorry about this @IainNZ, didn't know this was not good practice, I will be submitting PRs on metadata from now on :) As for now, what should I do to get things fixed?

**Comment by IainNZ** [comment]
I'm going to revert the commit, can try tagging new releases properly.

The message on Travis seems correct - its trying to test a version of Lora that works only on Julia 0.3, but its trying to test it on Julia 0.4 (nightly).

**Comment by IainNZ** [comment]
Ok its reverted now.

I'll submit a PR with an updated `.travis.yml`, the style is a bit out of date now.

**Comment by scidom** [comment]
Thanks @IainNZ, appreciated. I will be submitting PRs from now on, wasn't aware that my metadata approach was out of date :+1:

**Comment by IainNZ** [comment]
No problem

**Comment by scidom** [comment]
I will close this issue now, since it is all fixed, thanks! By the way, @davidanthoff, now you should be able to use Lora via the package manager without any metadata issues.
