### ISSUE TITLE
Making gradient work with lowered code

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Lora.jl#109]
@jrevels, @mlubin, I made a first attempt to integrate Lora with ForwardDiff and i ran into a problem. I know what the problem is but I don't know what is the Julia solution to it, so I thought I may bring it up. In brief, the question boils down to how one evaluates/interprets lowered code in Julia. In what follows, I will try to elaborate.

To start with, let me expose the problem at a high level. The following code

```
using Lora

f(x::Vector) = -dot(x, x)
Lora.codegen_internal_variable_method(f, [:logtarget])
```

yields the intended internal expression for the log-target

```
:(function ##internal_variable_method#7621(_state,_states)
        _state.logtarget = -((Main.dot)(_state.value,_state.value))
    end)
```

which I then evaluate. However, trying the following 

```
using ForwardDiff
using Lora

f(x::Vector) = -dot(x, x)
g = ForwardDiff.gradient(f)
Lora.codegen_internal_variable_method(g, [:gradlogtarget])
```

gives the following expression for the grad-log-target:

```
:(function ##internal_variable_method#7570(_state,_states)
        _state.gradlogtarget = (top(kwcall))((top(getfield))(ForwardDiff,:call),2,:chunk_size,chunk_size,:cache,cache,ForwardDiff.gradient,(top(Array))(top(Any),4),f,_state.value,A)
    end)
```

The obvious issue here is that in the latter expression for the gradient of the log-target there is additional info such as the chunk size, which has been lost down the way, because I passed from lowered code to a new top level expression (the one shown just above).

The solution would be to avoid defining a new top level expression for new methods, but instead interpret the lowered code (after any processing of it). To evaluate a top level expression, one can use `eval()`. Do you happen to know how one can evaluate/interpret/compile instead lowered expressions? In other words, if one has acquired (using pseudo-code here) `exprn = code_lowered(f, (Any,))`, how can he then interpret `exprn` (as `eval(exprn)` won't work on lowered_code)?

**Comment by scidom** [comment]
I found one solution, which allows to run Lora with ForwardDiff! I just avoided using code lowering, which seems that it can be potentially fragile anyhow, as I read online that it is not meant to be a fully-fledged API. So here is an example of running the Metropolis-adjusted Lagnevin Algorithm (MALA) with gradients computed via ForwardDiff!

```
using ForwardDiff
using Lora

f(x::Vector) = -dot(x, x)
g = ForwardDiff.gradient(f)

p = BasicContMuvParameter(:p, 1,
  logtarget=(state, states) -> state.logtarget = f(state.value),
  gradlogtarget=(state, states) -> state.gradlogtarget = g(state.value)
)

model = single_parameter_likelihood_model(p)

### Set driftstep to 0.9

sampler = MALA(0.9)

mcrange = BasicMCRange(nsteps=10000, burnin=1000)

v0 = Dict(:p=>[5.1, -0.9])

### Save grad-log-target along with the chain (value and log-target)

outopts = Dict{Symbol, Any}(:monitor=>[:value, :logtarget, :gradlogtarget], :diagnostics=>[:accept])

job = BasicMCJob(model, sampler, mcrange, v0, tuner=VanillaMCTuner(verbose=true), outopts=outopts)

@time chain = run(job)

chain.gradlogtarget

[mean(chain.value[i, :]) for i in 1:2]
```

**Comment by scidom** [comment]
P.S. I will need of course to hide the implementation details, but this shows in principle it works! I will close the issue now :)

**Comment by scidom** [comment]
On a second thought, I will keep this issue open until I integrate the above solution to Lora and make sure ForwardDiff works with it. Next will come ReverseDiffSource, and we can even compare the two autodiff approaches for MCMC simulations in terms of their speed.

**Comment by jrevels** [comment]
+1

**Comment by scidom** [comment]
This has now been addressed. Lora is connected with ForwardDiff (have added a simple example in Lora's README). There are a few more issues in Lora related to autodiff functionality, related to both ForwardDiff and ReverseDiffSource. I will open more specific issues to track the remaining matters.
