### ISSUE TITLE
Truncated normal RWM and Metropolis-within-Gibbs?

### ISSUE THREAD

**Issue by sdwfrost** [JuliaStats/Lora.jl#11]
@scidom and @fredo-dedup - Great job so far on MCMC.jl. I had already tweaked RWM.jl to accept a vector of scale parameters, but it looks as though you're already on top of this. A few requests (that I am happy to help with):

1. Using a truncated normal distribution rather than a normal in RWM.jl (with the appropriate Hastings ratio adjustment)
2. An integer random walk sampler (sampled from +/- 1:K), again with the choice of bounds.
3. Some means of collecting individual samplers together to perform Metropolis-within-Gibbs (or componentwise Metropolis, etc.), either with a fixed or random order.

**Comment by scidom** [comment]
The new graph-based model is now ready to accommodate Gibbs and Metropolis-within-Gibbs relatively easily. I will only need to set up a Gibbs-related job over the next few weeks (which has been logged already as an issue). As for the truncated normal, we haven't added this functionality yet. I will close this issue and will split it into sub-issues to track it better.
