### ISSUE TITLE
Add Metropolis sampler for discrete parameters

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Lora.jl#119]
See also #11.

**Comment by sdwfrost** [comment]
Thanks @scidom!

**Comment by scidom** [comment]
You are welcome @sdwfrost, I added an example under doc/examples/poisson/MH.jl on how to sample from an unnormalized Poisson target using a symmetric transition (proposal). The transition is defined by `prandproposal` and passed as an argument to the `MH` sampler. I tested the output by plotting the histogram of the chain against the actual pdf of the associated Poisson(λ=6) and they pretty much coincide.

You also mentioned the possibility of using a truncated normal as a proposal, which by now should work out of the box, though I will add a relevant example and documentation from this week onwards.
