### ISSUE TITLE
Julia 0.5 support?

### ISSUE THREAD

**Issue by jeff-regier** [JuliaStats/Lora.jl#144]
Is Julia 0.5 support in the works? We're interested in using Lora.jl over at [Celeste.jl](https://github.com/jeff-regier/Celeste.jl), but we have to stick with Julia 0.5 because we need multithreading. Thanks!

**Comment by scidom** [comment]
Thanks for getting in touch @jeff-regier. Yes, I will try to sort out Lora's compatibility with Julia 0.5. I will start by following up two well-known breakages, referencing the current issue so that you can follow the developments.

**Comment by scidom** [comment]
@jeff-regier, I tried to find and download a Julia 0.5 binary for Mac OS X, and there seems to be only 0.4.6 and 6.0 at http://julialang.org/downloads/ - may I ask where from you downloaded the 0.5 version? Thanks for the help!

**Comment by ararslan** [comment]
You should be able to get it from https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5-latest-osx10.7+.dmg

**Comment by scidom** [comment]
Thanks for the link, @ararslan, I downloaded it now!

**Comment by scidom** [comment]
I think that my latest commit must have ensured that Lora works with Julia 0.5, but if you run into any issues, let me know @jeff-regier 

cc @davidanthoff

**Comment by jeff-regier** [comment]
Thanks a lot @scidom ! Looks like unit tests are all passing on 0.5. We'll let you know how it goes.

CC @andymiller
