### ISSUE TITLE
Avoid allocating memory

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/Lora.jl#3]
The current codebase seems to be a little liberal with memory. If we're hoping to achieve good performance, we probably need to avoid lines like:

    oldbeta = copy(beta)
    beta += randn(model.size) * scale

I'm still working through everything, but this code seems to involve allocating a new vector for every sample, which we shouldn't really be doing. At least in principle, we can perform all memory allocation at the start of an MCMC run.

**Comment by scidom** [comment]
Memory is now allocated at the start of MCMC, minimising garbage collection and memory allocation. There is a minimal number of `copy()` calls only when it is necessary to copy states in case of acceptance.
