### ISSUE TITLE
Making MCMC.jl more flexible and portable in terms of model specification

### ISSUE THREAD

**Issue by papamarkou** [JuliaStats/Lora.jl#35]
@LaurenceA, your suggestion in #34 to somehow allow use of MCMCChain and samples with external models is very useful. I want to work towards this direction and my first impression is that your suggestion is feasible and attainable. I would like to ask you for some input, from a user's perspective in order to see how exactly I am going to achieve the end goal.

Let's say that you have a matrix of Monte Carlo samples that you have somehow computed. This matrix will populate the `MCMCChain.samples` field. You may (or may not) have the relevant scores (grad of the log-likelihood for instance) stored in a separate matrix, which could populate the `MCMCChain.gradients` field. Assuming this situation, I would like to ask you the following:
- you will also need to have a task defined, since this is one of the main components of the `MCMC` package. There is a reason of course for this, since tasks make it much easier to handle the simulations. This task needs in turn a triplet (model, sampler, runner) as its fields. The sampler and runner are easy to be instantiated using the existing samplers and runners. What you want is to define your own model rather than using the likelihood model of the `MCMC` package. Do I understand correct what you are trying to achieve?
- If so, you would have to define this model as a subtype of `MCMCModel` or else we would have to simply change the `MCMCTask.model` field so as to be a subtype of `Model` instead of `MCMCModel`. The main question is what kind of statistical model you want to define. This is a more general question, since one may want to input here a model from `GLM` or from any other Julia package. @fredo-dedup, @johnmyleswhite, @dmbates, @andreasnoackjensen, @lindahua I am copying you in here so that you follow up the discussion (and so that you contribute if you have some ideas). If you can all give me an idea of possible models and situations that one may want to use with `MCMC` then I can start extending the codebase in `MCMC` to better work with external models.

**Comment by juanpide** [comment]
What is more powerful now, Stan, DynamicHMC.jl, Lora.jl, Mamba.jl, Klara.jl...?
Faster and converges with difficult problems.
What I don't like about Stan is it isn't easy to deal with discrete parameters, and you need an external program (and language).
