### ISSUE TITLE
Write MCMCTask{R<:MCMCRunner}

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaStats/Lora.jl#61]
In runners.jl there is a lot of manual type checking (`isa(t.runner, SerialMC)`)

Would it be better to parameterize the `MCMCTask` type on the type of the runner so that it can be dispatched via julia's type checking rather than manually checking types?

**Comment by scidom** [comment]
The new design of Lora has changed so drastically in the current version (not pushed yet to METADATA) that this issue does not arise in the newly designed code, so I will close this.
